### PR TITLE
fix(access): 🐛  show edit option only for members

### LINKED ISSUE #9: Fix edit option showing for non members
### Describe the Bug

It should show only for OWNER, ADMIN, MEMBER roles

### PR DESCRIPTION
**Pull request by MuruganandamVG**
Resolves #9

### CODE REVIEW

**Comment by MuruganandamVG** [comment]
@mcnaveen  Please review this PR

**Comment by mcnaveen** [comment]
Hi @MuruganandamVG You haven't signed the CLA yet. Click this link to continue.
https://cla-assistant.io/mcnaveen/liny?pullRequest=21

File: components/posts/card.tsx [hunk 1]
```diff
@@ -38,6 +38,7 @@ export const PostsCard: React.FC<PostsCardProps> = ({
   post,
   layout = "compact",
   currentUserId,
+  hasAccess,
```
Comment (mcnaveen) [inline components/posts/card.tsx:42]: `hasAccess` needs to be added in the `PostsCardProps` interface under the `currentUserId` on Line 34

`hasAccess` is type boolean.

**Comment by MuruganandamVG** [comment]
Hi @mcnaveen  I have signed the CLA agreement now

File: components/posts/card.tsx (hunk 1 above)
Comment (mcnaveen) [reply components/posts/card.tsx:42]: Is the build failing when you try to run `pnpm run build`? Can you please test it?

Because the preview deployment is failing.

5TQLnJdLGnTO1tEW000019

**Review by mcnaveen — APPROVED** [review]

**Comment by mcnaveen** [comment]
LGTM 🥳

**Comment by mcnaveen** [comment]
Hi @MuruganandamVG Thank you so much for your contribution! 🥇

**Comment by MuruganandamVG** [comment]
> Hi @MuruganandamVG Thank you so much for your contribution! 🥇

No Problem @mcnaveen , will try to contribute more

**Comment by mcnaveen** [comment]
@all-contributors please add @MuruganandamVG for code
